[project]
name = "persona-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.107.2",
    "flask>=2.3.0",
    "flask-socketio>=5.3.0",
    "python-dotenv>=1.0.0",
]
